### ISSUE TITLE
Crash exporting scores on Windows

### ISSUE THREAD

**Issue by oliverdunk** [oliverdunk/NertsPlus#4]
It looks like something is causing a crash when trying to export scores on Windows:

```
Absolute path information is required.
   at System.Security.Util.StringExpressionSet.CreateListFromExpressions(String[] str, Boolean needFullPath)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Reflection.Assembly.LoadFile(String path)
   at NertsPlus.ExportScores.GetName(NetID id)
   at NertsPlus.ExportScores.Update(CompletionScreen __instance)
   at CompletionScreen.Update_Patch1(CompletionScreen this, Single timeDelta)
   at ScreenStack.smethod_3(IScreen iscreen_0, Single float_2, Boolean bool_0, GStruct0`1 gstruct0_0)
   at ScreenStack.Class63.method_0(GStruct5 gstruct5_0)
   at GClass15.method_15(Action`1 action_0, Action`1 action_1, Action`1 action_2, Action`1 action_3, Action`1 action_4)
   at ScreenStack.smethod_2(Single float_2)
   at GameLogic.method_13()
   at GClass39.Main(String[] args)
```

**Comment by oliverdunk** [comment]
Resolved in https://github.com/oliverdunk/NertsPlus/commit/ba4553804bb5c696ee5e8453f18df1abf26c05e2
